### ISSUE TITLE
default username(email) and password

### ISSUE THREAD

**Issue by wenzizone** [Email-Dashboard/Email-Marketing#52]
after i start up all the service with docker-compose command
then ,what's the default username(email) and password for login.
i couldn't found it.
i also change follow environment. but still can not login
      SIDEKIQ_USERNAME: sidekiqUsername
      SIDEKIQ_PASSWORD: sidekiqPass

**Comment by muhammet** [comment]
You need to create a account in the rails console in the docker

Account.create(email: "my@email.com", password: "yourpassword", password_confirmation: "yourpasword")

**Comment by wenzizone** [comment]
well, thank you i'll try

**Comment by cypriotxx** [comment]
i cant see how to do this, how did you get it going ?

![image](https://user-images.githubusercontent.com/35560135/73216314-aa14d280-414d-11ea-9537-9dacac93562f.png)

**Comment by sadikay** [comment]
@cypriotxx after connecting to the container you need to run `bundle exec rails c production` here. Then your create command must work.

**Comment by cypriotxx** [comment]
![image](https://user-images.githubusercontent.com/35560135/73259806-7a52e280-41c0-11ea-8cc1-0e45557d52c6.png)
